[build]
target = "thumbv7em-none-eabihf"

[target.thumbv7em-none-eabihf]
rustflags = [
    "-C", "link-arg=-Tlink.x",
    "-C", "link-arg=-Tdefmt.x",
    ]
runner = "probe-rs run --chip nRF52833_xxAA"

[env]
DEFMT_LOG = "trace"
DEFMT_RTT_BUFFER_SIZE = "1024"
