[workspace]
resolver ="2"

members = [
    "adder",
    "sort",
    "hello-rust",
    "minigrep",
    "pointer",
    "mocking",
    "thread",
    "mutex",
    "oop",
    "blog",
    "blog-2", 
    "timer_future", "toki",
]



